### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by mahbubul14** [mahbubul14/The-New-York-Times#2]

**Comment by Abhi-1725** [comment]
use grid and flex

**Comment by igorkol91** [comment]
You should probably use position apsolute for the editor's picks and just align them with right:

**Comment by vikitaotiz** [comment]
You have made amazing progress so far.... Just work on the css to make it look nicer.

**Comment by mahbubul14** [comment]
I solved it all. Thanks for the feedback.
