### ISSUE TITLE
Alan's code review

### ISSUE THREAD

**Issue by Mhdez221993** [mahbubul14/The-New-York-Times#4]
1. Put a meaningful name on the title of your website
2. Use icons instead of SVG 
3. remove spaces between on HTML file (class   =   "writer")
4.theory of inflation should have a max of 1200px
5 Apply figure to images
6 Fill alt=" " attributes with a meaningful explanation

recommendation:  To position an image absolute(or any element) the container should be position relative.

**Comment by 1v4n4** [comment]
You can make missing part using flex or grid. Check the syntax, for the typing errors

**Comment by mahbubul14** [comment]
The suggestions were really helpful. I implemented it and it looks nice now.
